[package]
edition.workspace = true
name = "tansa-protocol"
publish.workspace = true
version.workspace = true

[dependencies]
tonic = "0.11"
prost = "0.12"
prost-types = "0.12"

[build-dependencies]
tonic-build = "0.11"
